version: '3'
services:
  db:
    image: postgres:9.6.16
    volumes:
      - postgresql_data:/var/lib/postgresql/data:cached
  web:
    image: diveintohacking/docker-compose-rails-6:0.0.4
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
    environment:
      - BUNDLE_PATH=/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  postgresql_data:
